CREATE TABLE tb_master_nspk (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nspk VARCHAR(255) NOT NULL,
    kode_opd VARCHAR(255) DEFAULT'',
    tahun INT(50) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);