CREATE TABLE tb_pptk (
   id BIGINT AUTO_INCREMENT PRIMARY KEY,
   nip VARCHAR(255) NOT NULL,
   kode_opd VARCHAR(255) NOT NULL,
   tahun INT NOT NULL,
   kode_sub_kegiatan VARCHAR(255) NOT NULL,
   nip_atasan VARCHAR(255) DEFAULT NULL,
   aktif_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   nonaktif_at TIMESTAMP DEFAULT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);