CREATE TABLE tb_ikk (
    id INT AUTO_INCREMENT PRIMARY KEY,
    kode_bidang_urusan VARCHAR(255) NOT NULL,
    jenis VARCHAR(255) NOT NULL,
    nama_indikator VARCHAR(255) NOT NULL,
    target VARCHAR(255) NOT NULL,
    satuan VARCHAR(255) NOT NULL,
    keterangan TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);