CREATE TABLE tb_isu_global (
    id INT AUTO_INCREMENT PRIMARY KEY,
    kode_bidang_urusan VARCHAR(255) NOT NULL,
    isu_global VARCHAR(255) NOT NULL,
    kode_opd VARCHAR(255) DEFAULT'',
    tahun INT(50) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);