CREATE TABLE tb_arah_kebijakan (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pokin_id INT(50) DEFAULT 0,
    arah_kebijakan VARCHAR(255) DEFAULT'',
    kode_opd VARCHAR(255) DEFAULT'',
    tahun INT(50) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);