CREATE TABLE tb_jenis_inovasi (
    id INT AUTO_INCREMENT PRIMARY KEY,
    jenis VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);